describe('sidebar navigation', () => {
  it('navigates via the sidebar and marks the active link', () => {
    cy.visit('/login')
    cy.get('#email').type('alice.thompson@company.com')
    cy.get('#password').type('Password123!')
    cy.contains('button', 'Sign in').click()
    cy.url().should('include', '/admin')

    cy.get('[data-testid="sidebar"]').contains('a', 'Employees').click()
    cy.url().should('include', '/admin/employees')
    cy.get('[data-testid="sidebar"]')
      .contains('a', 'Employees')
      .should('have.attr', 'aria-current', 'page')
    cy.get('[data-testid="screen-employees"]').should('be.visible')

    cy.get('[data-testid="sidebar"]').contains('a', 'Dashboard').click()
    cy.url().should('match', /\/admin$/)
    cy.get('[data-testid="sidebar"]')
      .contains('a', 'Dashboard')
      .should('have.attr', 'aria-current', 'page')
    cy.get('[data-testid="sidebar"]')
      .contains('a', 'Employees')
      .should('not.have.attr', 'aria-current')
  })
})
